### ISSUE TITLE
Effectiveness compared to react-redux

### ISSUE THREAD

**Issue by ansonkao** [mijime/mithril-redux-starter-hmr#1]
Hey @mijime!

Cool repo. I'm curious if you've used react-redux and could offer your thoughts on how Mithril fares in the place of React? Have you tried using Mithril.js via the component pattern?

Cheers,
Anson

**Comment by mijime** [comment]
Thank you for looking at the repository !

However, this repository is a sample project that tried browserify-hmr. 
I understanding of react and mithril is not enough.

Sorry...
